services:
    mysql:
        image: mysql:8.0
        container_name: mysql-container
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: taskmanagementdb
        ports:
            - "3306:3306"
        volumes:
            - data:/var/lib/mysql
        healthcheck:
              test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
              interval: 5s
              timeout: 5s
              retries: 5
    
    app:
        image: taskmanagementapp
        ports:
            - "8080:8080"
        depends_on:
            mysql:
                condition: service_healthy
        environment:
            SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/taskmanagementdb?useTimezone=True&serverTimezone=UTC
            SPRING_DATASOURCE_USERNAME: root
            SPRING_DATASOURCE_PASSWORD: root
        restart: on-failure
volumes:
    data:
