services:
    mysql:
        image: mysql:8.0
        container_name: mysql-container
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: SS_user_auth
        ports:
            - "3306:3306"
        volumes:
            - data:/var/lib/mysql

    app:
        image: taskmanagementapp
        ports:
            - "8080:8080"
        depends_on:
            - mysql
        environment:
            SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/SS_user_auth?useTimezone=True&serverTimezone=UTC
            SPRING_DATASOURCE_USERNAME: root
            SPRING_DATASOURCE_PASSWORD: root
volumes:
    data:
