services:
    mysql:
        image: mysql:8.0
        container_name: mysql-container
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: SS_user_auth
            MYSQL_USER: root
            MYSQL_PASSWORD: root
        ports:
            - "3306:3306"
        volumes:
        - data:var/lib/mysql
        restart: unless-stopped

volumes:
    data: